name: Auto Sign

on:
  schedule:
    - cron: '30 23,9 * * *'  # UTC 时间 23:30 (北京时间 7:30) 和 9:00 (北京时间 17:00)
  workflow_dispatch:  # 支持手动触发

jobs:
  sign:
    runs-on: ubuntu-latest
    timeout-minutes: 5  # 添加超时限制
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    
    - name: Install dependencies
      run: |
        pip install requests
        pip install pillow
    
    - name: Create image file
      run: |
        echo "${{ secrets.SIGN_IMAGE }}" | base64 -d > img.jpg
    
    - name: Run sign script
      env:
        USERS_CONFIG: ${{ secrets.USERS_CONFIG }}
      run: |
        python auto_sign.py 